# Generated by Django 5.2.17 on 2026-10-05 12:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerfil',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rol', models.CharField(choices=[('propietario', 'Propietario'), ('encargado', 'Encargado'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20)),
                ('debe_cambiar_clave', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Perfil',
                'verbose_name_plural': 'historical Perfiles',
                'db_table': 'perfiles_historial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rol', models.CharField(choices=[('propietario', 'Propietario'), ('encargado', 'Encargado'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20)),
                ('debe_cambiar_clave', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerfilTelefono',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('es_principal', models.BooleanField(default=False)),
                ('codigo_pais', models.CharField(choices=[('+54', 'AR (+54)'), ('+56', 'CL (+56)'), ('+57', 'CO (+57)'), ('+593', 'EC (+593)'), ('+52', 'MX (+52)'), ('+51', 'PE (+51)'), ('+1-809', 'DO (+1-809)'), ('+598', 'UY (+598)'), ('+58', 'VE (+58)')], default='+56', max_length=8)),
                ('numero', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'El número solo debe contener dígitos.')])),
                ('tipo', models.CharField(choices=[('movil', 'Móvil'), ('fijo', 'Fijo')], default='movil', max_length=10)),
                ('tiene_whatsapp', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.perfil')),
            ],
            options={
                'verbose_name': 'historical Teléfono del equipo',
                'verbose_name_plural': 'historical Teléfonos del equipo',
                'db_table': 'perfiles_telefonos_historial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerfilDireccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('es_principal', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=30)),
                ('calle', models.CharField(max_length=150)),
                ('numero', models.CharField(blank=True, default='', max_length=15)),
                ('complemento', models.CharField(blank=True, default='', max_length=60)),
                ('comuna', models.CharField(blank=True, default='', max_length=80)),
                ('ciudad', models.CharField(blank=True, default='', max_length=80)),
                ('region', models.CharField(blank=True, default='', max_length=80)),
                ('pais', models.CharField(default='CL', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Usa el código de país de dos letras en mayúscula (CL, PE, CO).')])),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=12)),
                ('referencia', models.CharField(blank=True, default='', max_length=150)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.perfil')),
            ],
            options={
                'verbose_name': 'historical Dirección del equipo',
                'verbose_name_plural': 'historical Direcciones del equipo',
                'db_table': 'perfiles_direcciones_historial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PerfilDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('es_principal', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=30)),
                ('calle', models.CharField(max_length=150)),
                ('numero', models.CharField(blank=True, default='', max_length=15)),
                ('complemento', models.CharField(blank=True, default='', max_length=60)),
                ('comuna', models.CharField(blank=True, default='', max_length=80)),
                ('ciudad', models.CharField(blank=True, default='', max_length=80)),
                ('region', models.CharField(blank=True, default='', max_length=80)),
                ('pais', models.CharField(default='CL', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Usa el código de país de dos letras en mayúscula (CL, PE, CO).')])),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=12)),
                ('referencia', models.CharField(blank=True, default='', max_length=150)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='profiles.perfil')),
            ],
            options={
                'verbose_name': 'Dirección del equipo',
                'verbose_name_plural': 'Direcciones del equipo',
                'db_table': 'perfiles_direcciones',
            },
        ),
        migrations.CreateModel(
            name='PerfilTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('es_principal', models.BooleanField(default=False)),
                ('codigo_pais', models.CharField(choices=[('+54', 'AR (+54)'), ('+56', 'CL (+56)'), ('+57', 'CO (+57)'), ('+593', 'EC (+593)'), ('+52', 'MX (+52)'), ('+51', 'PE (+51)'), ('+1-809', 'DO (+1-809)'), ('+598', 'UY (+598)'), ('+58', 'VE (+58)')], default='+56', max_length=8)),
                ('numero', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'El número solo debe contener dígitos.')])),
                ('tipo', models.CharField(choices=[('movil', 'Móvil'), ('fijo', 'Fijo')], default='movil', max_length=10)),
                ('tiene_whatsapp', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=30)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='profiles.perfil')),
            ],
            options={
                'verbose_name': 'Teléfono del equipo',
                'verbose_name_plural': 'Teléfonos del equipo',
                'db_table': 'perfiles_telefonos',
            },
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'propietario')), fields=('rol',), name='perfiles_un_propietario'),
        ),
        migrations.AddConstraint(
            model_name='perfildireccion',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('perfil',), name='profiles_perfildireccion_un_principal'),
        ),
        migrations.AddConstraint(
            model_name='perfildireccion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitud__isnull', True), ('longitud__isnull', True)), models.Q(('latitud__isnull', False), ('longitud__isnull', False)), _connector='OR'), name='profiles_perfildireccion_coordenadas_completas'),
        ),
        migrations.AddConstraint(
            model_name='perfiltelefono',
            constraint=models.UniqueConstraint(fields=('perfil', 'codigo_pais', 'numero'), name='profiles_perfiltelefono_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='perfiltelefono',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('perfil',), name='profiles_perfiltelefono_un_principal'),
        ),
    ]
