from django.urls import path
from apps.appointments.views.calendar.view import CalendarView, CalendarListView
from apps.appointments.views.agenda import (
    AppointmentsView,
    AgendaListView,
    AgendaSeeModalView,
    AgendaUpdateModalView,
    AgendaCancelModalView,
    AgendaRestoreModalView,
    AgendaConfirmationModal,
    AgendaDeleteModalView,
)
from apps.appointments.views.agenda_create import (
    AgendaCreateView,
    ServiceDetailsAjax,
    AvailableHoursAjax,
)

urlpatterns = [
    path(
        "calendario/",
        CalendarView.as_view(),
        name="calendar",
    ),
    path(
        "calendario/lista/ajax/",
        CalendarListView.as_view(),
        name="calendar_list",
    ),
    path(
        "calendario/agenda/<str:date>/",
        AppointmentsView.as_view(),
        name="calendar_appointments",
    ),
    path(
        "calendario/agenda/<str:date>/crear/",
        AgendaCreateView.as_view(),
        name="create_appointment_from_calendar",
    ),
    path(
        "agenda/lista/ajax/",
        AgendaListView.as_view(),
        name="agenda_list",
    ),
    path(
        "agenda/detalle/<str:pk>/editar/modal/",
        AgendaUpdateModalView.as_view(),
        name="agenda_update_modal",
    ),
    path(
        "agenda/detalle/<str:pk>/ver/modal/",
        AgendaSeeModalView.as_view(),
        name="agenda_see_modal",
    ),
    path(
        "agenda/detalle/<str:pk>/confirmar/modal/",
        AgendaConfirmationModal.as_view(),
        name="agenda_confirmation_modal",
    ),
    path(
        "agenda/detalle/<str:pk>/cancelar/modal/",
        AgendaCancelModalView.as_view(),
        name="agenda_cancel_modal",
    ),
    path(
        "agenda/detalle/<str:pk>/restaurar/modal/",
        AgendaRestoreModalView.as_view(),
        name="agenda_restore_modal",
    ),
    path(
        "agenda/detalle/<str:pk>/eliminar/modal/",
        AgendaDeleteModalView.as_view(),
        name="agenda_delete_modal",
    ),
    path(
        "agenda/servicio/detalles/ajax/",
        ServiceDetailsAjax.as_view(),
        name="service_details_ajax",
    ),
    path(
        "agenda/horas/disponibles/ajax/",
        AvailableHoursAjax.as_view(),
        name="available_hours_ajax",
    ),
]
