from django.urls import path
from apps.appointments.views.agenda import (
    AppointmentsView,
    AgendaListView,
    AgendaUpdateModalView,
    AgendaCancelModalView,
    AgendaConfirmationModal,
    AgendaDeleteModalView,
)
from apps.appointments.views.agenda_create import (
    AgendaCreateView,
    ServiceDetailsAjax,
    AvailableHoursAjax,
)

urlpatterns = [
    path(
        "agenda/",
        AppointmentsView.as_view(),
        name="appointments",
    ),
    path(
        "agenda/lista/ajax/",
        AgendaListView.as_view(),
        name="agenda_list",
    ),
    path(
        "agenda/crear",
        AgendaCreateView.as_view(),
        name="agenda_create",
    ),
    path(
        "agenda/detalle/<str:pk>/editar/modal/",
        AgendaUpdateModalView.as_view(),
        name="agenda_update_modal",
    ),
    path(
        "agenda/detalle/<str:pk>/confirmar/modal/",
        AgendaConfirmationModal.as_view(),
        name="agenda_confirmation_modal",
    ),
    path(
        "agenda/detalle/<str:pk>/cancelar/modal/",
        AgendaCancelModalView.as_view(),
        name="agenda_cancel_modal",
    ),
    path(
        "agenda/detalle/<str:pk>/eliminar/modal/",
        AgendaDeleteModalView.as_view(),
        name="agenda_delete_modal",
    ),
    path(
        "agenda/servicio/detalles/ajax/",
        ServiceDetailsAjax.as_view(),
        name="service_details_ajax",
    ),
    path(
        "agenda/horas/disponibles/ajax/",
        AvailableHoursAjax.as_view(),
        name="available_hours_ajax",
    ),
]
