from django.urls import path
from apps.services.views.servicio import (
    ServicesView,
    ServiceListView,
    ServiceCreateModalView,
    ServiceDetailModalView,
    ServiceDeleteModalView,
)
from apps.services.views.categories.categoria import (
    CategoriesView,
    CategoryListView,
    CategoryCreateModalView,
    CategoryDetailModalView,
    CategoryDeleteModalView,
)

urlpatterns = [
    path(
        "servicios/",
        ServicesView.as_view(),
        name="services",
    ),
    path(
        "servicios/lista/ajax",
        ServiceListView.as_view(),
        name="service_list",
    ),
    path(
        "servicios/crear/",
        ServiceCreateModalView.as_view(),
        name="service_create_modal",
    ),
    path(
        "servicios/<int:pk>/detalle/",
        ServiceDetailModalView.as_view(),
        name="service_detail_modal",
    ),
    path(
        "servicios/<int:pk>/eliminar/",
        ServiceDeleteModalView.as_view(),
        name="service_delete_modal",
    ),
    path(
        "categorias/",
        CategoriesView.as_view(),
        name="categories",
    ),
    path(
        "categorias/lista/ajax",
        CategoryListView.as_view(),
        name="category_list",
    ),
    path(
        "categorias/crear/",
        CategoryCreateModalView.as_view(),
        name="category_create_modal",
    ),
    path(
        "categorias/<int:pk>/detalle/",
        CategoryDetailModalView.as_view(),
        name="category_detail_modal",
    ),
    path(
        "categorias/<int:pk>/eliminar/",
        CategoryDeleteModalView.as_view(),
        name="category_delete_modal",
    ),
]
