from django.urls import path
from apps.services.views.servicio import (
    ServicesView,
    ServiceListView,
    ServiceExportView,
    ServiceCreateModalView,
    ServiceDetailModalView,
    ServiceDeleteModalView,
)
from apps.services.views.categories.categoria import (
    CategoriesView,
    CategoryListView,
    CategoryExportView,
    CategoryCreateModalView,
    CategoryDetailModalView,
    CategoryDeleteModalView,
)
from apps.services.views.imports import (
    ServiceImportView,
    ServiceExampleExportView,
)

urlpatterns = [
    path(
        "servicios/",
        ServicesView.as_view(),
        name="services",
    ),
    path(
        "servicios/lista/ajax",
        ServiceListView.as_view(),
        name="service_list",
    ),
    path(
        "servicios/exportar/",
        ServiceExportView.as_view(),
        name="service_export",
    ),
    path(
        "servicios/importar/",
        ServiceImportView.as_view(),
        name="service_import",
    ),
    path(
        "servicios/importar/plantilla/",
        ServiceExampleExportView.as_view(),
        name="service_example_export",
    ),
    path(
        "servicios/crear/",
        ServiceCreateModalView.as_view(),
        name="service_create_modal",
    ),
    path(
        "servicios/<int:pk>/detalle/",
        ServiceDetailModalView.as_view(),
        name="service_detail_modal",
    ),
    path(
        "servicios/<int:pk>/eliminar/",
        ServiceDeleteModalView.as_view(),
        name="service_delete_modal",
    ),
    path(
        "categorias/",
        CategoriesView.as_view(),
        name="categories",
    ),
    path(
        "categorias/lista/ajax",
        CategoryListView.as_view(),
        name="category_list",
    ),
    path(
        "categorias/exportar/",
        CategoryExportView.as_view(),
        name="category_export",
    ),
    path(
        "categorias/crear/",
        CategoryCreateModalView.as_view(),
        name="category_create_modal",
    ),
    path(
        "categorias/<int:pk>/detalle/",
        CategoryDetailModalView.as_view(),
        name="category_detail_modal",
    ),
    path(
        "categorias/<int:pk>/eliminar/",
        CategoryDeleteModalView.as_view(),
        name="category_delete_modal",
    ),
]
