# Generated by Django 5.2.17 on 2026-10-05 12:11

from django.db import migrations

RUBROS = [
    ("unas", "Manicure y uñas"),
    ("barberia", "Barbería"),
    ("peluqueria", "Peluquería"),
    ("estetica", "Estética y spa"),
    ("salud", "Salud y bienestar"),
    ("otro", "Otro"),
]


def crear_rubros(apps, schema_editor):
    Rubro = apps.get_model("tenancy", "Rubro")
    for orden, (codigo, nombre) in enumerate(RUBROS, start=1):
        Rubro.objects.get_or_create(codigo=codigo, defaults={"nombre": nombre, "orden": orden})


def borrar_rubros(apps, schema_editor):
    Rubro = apps.get_model("tenancy", "Rubro")
    Rubro.objects.filter(codigo__in=[codigo for codigo, _ in RUBROS], negocios__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_personas_rubros_y_negocio_completo'),
    ]

    operations = [
        migrations.RunPython(crear_rubros, borrar_rubros),
    ]
