# Generated by Django 4.2.23 on 2025-08-10 19:31

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion_estimada',
            field=models.DurationField(blank=True, null=True, validators=[utils.validators.validate_duracion_positiva]),
        ),
    ]
