# Generated by Django 4.2.23 on 2026-07-12 21:25

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TareaEnProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_proceso', models.CharField(max_length=100)),
                ('origen', models.CharField(db_index=True, max_length=50)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('fallido', 'Fallido')], db_index=True, default='pendiente', max_length=20)),
                ('progreso_actual', models.PositiveIntegerField(default=0)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('datos_entrada', models.JSONField(blank=True, default=dict)),
                ('resultado_metadata', models.JSONField(blank=True, default=dict)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarea en proceso',
                'verbose_name_plural': 'Tareas en proceso',
                'db_table': 'tareas_en_proceso',
                'ordering': ['-created'],
            },
        ),
    ]
