# Generated by Django 4.2.23 on 2026-07-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaenproceso',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
