# Generated by Django 4.2.23 on 2026-01-24 00:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('monto_total_cita', models.DecimalField(decimal_places=2, help_text='Monto total que debe pagarse por la cita', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('REEMBOLSADO', 'Reembolsado'), ('IMPAGO', 'Impago')], db_index=True, default='PENDIENTE', max_length=20)),
                ('cliente_nombre', models.CharField(help_text='Nombre del cliente al momento de crear el pago (snapshot)', max_length=200)),
                ('fecha_cita', models.DateTimeField(help_text='Fecha y hora de la cita (snapshot)')),
                ('fecha_pago_completado', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora en que el pago se completó totalmente', null=True)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Descuento total aplicado al pago', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='appointments.cita')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPago',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('monto_total_cita', models.DecimalField(decimal_places=2, help_text='Monto total que debe pagarse por la cita', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('REEMBOLSADO', 'Reembolsado'), ('IMPAGO', 'Impago')], db_index=True, default='PENDIENTE', max_length=20)),
                ('cliente_nombre', models.CharField(help_text='Nombre del cliente al momento de crear el pago (snapshot)', max_length=200)),
                ('fecha_cita', models.DateTimeField(help_text='Fecha y hora de la cita (snapshot)')),
                ('fecha_pago_completado', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora en que el pago se completó totalmente', null=True)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Descuento total aplicado al pago', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cita', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointments.cita')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pago',
                'verbose_name_plural': 'historical Pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDetallePago',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_pago', models.DateTimeField(help_text='Fecha y hora en que se realizó este pago específico')),
                ('monto_pago', models.DecimalField(decimal_places=2, help_text='Monto de este pago/abono específico', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de recibo, transacción, cheque, etc.', max_length=100, null=True)),
                ('notas_detalle', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.pago')),
            ],
            options={
                'verbose_name': 'historical Detalle de Pago',
                'verbose_name_plural': 'historical Detalles de Pago',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_pago', models.DateTimeField(help_text='Fecha y hora en que se realizó este pago específico')),
                ('monto_pago', models.DecimalField(decimal_places=2, help_text='Monto de este pago/abono específico', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de recibo, transacción, cheque, etc.', max_length=100, null=True)),
                ('notas_detalle', models.TextField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='payments.pago')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'db_table': 'detalle_pago',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
