# Generated by Django 4.2.23 on 2025-08-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
