# Generated by Django 4.2.23 on 2026-09-22 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPreference',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('scope', models.CharField(choices=[('user', 'Usuario'), ('salon', 'Salón')], default='user', max_length=20, verbose_name='Alcance')),
                ('scope_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Identificador del alcance')),
                ('key', models.CharField(max_length=100, verbose_name='Clave')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Valor')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Preferencia',
                'verbose_name_plural': 'historical Preferencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('user', 'Usuario'), ('salon', 'Salón')], default='user', max_length=20, verbose_name='Alcance')),
                ('scope_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Identificador del alcance')),
                ('key', models.CharField(max_length=100, verbose_name='Clave')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Valor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencia',
                'verbose_name_plural': 'Preferencias',
                'db_table': 'preference',
            },
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('scope', 'scope_id', 'key'), name='preference_scope_key_unique'),
        ),
        migrations.AddField(
            model_name='historicalpreference',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
