# Generated by Django 4.2.23 on 2025-08-04 00:06

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, unique=True, validators=[utils.validators.validate_telefono]),
        ),
    ]
