# Generated by Django 4.2.23 on 2025-11-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agenda', models.DateField()),
                ('hora_agenda', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['-fecha_agenda'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_acordado', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad_servicios', models.PositiveIntegerField(default=1)),
                ('notas_detalle', models.TextField(blank=True, null=True)),
                ('descuento', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='appointments.cita')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Cita',
                'verbose_name_plural': 'Detalles de Citas',
                'db_table': 'detalle_cita',
            },
        ),
    ]
