# Generated by Django 4.2.23 on 2025-12-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='creado_por',
        ),
    ]
